### ISSUE TITLE
Description under title

### ISSUE THREAD

**Issue by lfarah** [hachinobu/SamuraiTransition#36]
<img width="385" alt="screen shot 2017-02-14 at 12 16 46 pm" src="https://cloud.githubusercontent.com/assets/6511079/22932553/7a48b75a-f2af-11e6-9119-b7bdb6acf2fc.png">

**Comment by hachinobu** [comment]
@lfarah Thank you for registering the Issue.

<img width="994" alt="2017-02-15 9 15 41" src="https://cloud.githubusercontent.com/assets/1317847/22955431/5e3855a6-f35f-11e6-9be5-c8238c7f8a47.png">

fix this Issue.
