### ISSUE TITLE
Transition animation for navigation push view controller

### ISSUE THREAD

**Issue by hongmun** [hachinobu/SamuraiTransition#39]
Hello, is this possible to integrate with transition animation for navigation controller push to view controller?

**Comment by hachinobu** [comment]
@hongmun 
Hello.
Of course it is possible.

When using in the transition of the navigation controller, please specify the SamuraiTransition instance as the delegate of the navigation controller.

See the `horizontalZan(_ sender: Any)` method in the ViewController.swift of the Example project.
